---
- hosts: all
  become: yes
  tasks:
    - name: Add public key to remote server
      authorized_key:
        user: ubuntu
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"